### ISSUE TITLE
tiny bug ?

### ISSUE THREAD

**Issue by christinazavou** [roseDwayane/AIEEG#1]
Hello, 

thanks a lot for open sourcing your code for this interesting work!

I think there is a bug in [this line](https://github.com/roseDwayane/AIEEG/blob/f90fbca9dbb199a1819599601af2a116f01e6688/UNet1D-sim/train.py#L190): shouldn't it be ```output_freq = output_freq / torch.std(output_freq)``` ? 

Thanks in advance,
Christina

**Comment by roseDwayane** [comment]
Thanks for your reply!

I don't think it's a bug, but a checking mechanism to make sure the signal is correct. 

This line is intended to be used for standardization because the amplitude of the decoded signal was not enough to be trusted.

However, things are not as simple as imagined, and in the process of research, it is found that they are easily affected by extreme values.

So we use the pre-processed target signal as our standard deviation. If there is no accident, we expect the standard deviation here to be 1.

**Comment by roseDwayane** [comment]
Thank you for pointing this out.

However, since the standard deviation of the normalized target signal is 1, lines 190 (```output_freq = output_freq / torch.std(target_freq)```) and 191 (```target_freq = target_freq / torch.std(target_freq)```) are redundant and do not have any function. These two lines have been removed.

Thank you again.

**Comment by christinazavou** [comment]
Ok I see thanks. 

I also realized that in the simulated data, [this line](https://github.com/roseDwayane/AIEEG/blob/47428fc66eaea706084beb54a7d348ca7de26a19/UNet1D-sim/dataGenerator.py#L90) generates 19 identical signals for the 19 input/output channels. Was this on purpose or is it a mistake?

I also noticed using all the loss components:
```trainValidateSegmentation(args=model_train_parameter([1, 1, 1, 1], './' + name + '_Simulate_5', "./" + name + "_simulate_data/"))```
that loss1, loss2, loss3 lie within [0, 1] while loss4 is in the scale of hundreds.
Therefore I'm wondering if you used different data to generate the ensemble loss of figure 4?
